from __future__ import annotations
from typing import Any
import numpy as np,torch
from torch import nn
from envs.grid.core.grid_core import GridCore
from envs.grid.deployments import build_agent_deployments
SAFE_POC_ALGO_NAME='MATD3_SAFE_POC'
SAFETY_LOCAL_FIELD_NAMES='soc_raw','load_raw','pv_raw','battery_capacity_kwh','p_max_kw'
SAFETY_LOCAL_DIM=len(SAFETY_LOCAL_FIELD_NAMES)
_SAFETY_EPS=1e-06
_ACTION_TOL=1e-05
REMOVED_STEP_INFO_FIELDS=frozenset({'r_action_pen','r_soc_pen'})
def is_safe_poc_algorithm(cfg_or_name:Any)->bool:
	if isinstance(cfg_or_name,str):name=cfg_or_name
	else:algo_cfg=getattr(cfg_or_name,'algo',None);name=getattr(algo_cfg,'name','')
	return str(name)==SAFE_POC_ALGO_NAME
def reject_removed_step_info_fields(info:dict[str,Any],*,entrypoint:str)->None:
	removed=sorted(REMOVED_STEP_INFO_FIELDS.intersection(str(key)for key in dict(info).keys()))
	if removed:raise KeyError(f"{entrypoint} received old step info field(s) {removed}. r_action_pen / r_soc_pen were removed in fixMADRL section 5.3. Old rollout parquet or checkpoint-derived step info is no longer reusable; re-run notebooks/madrl/train_base.ipynb.")
def _row_norm_sq(rows:torch.Tensor)->torch.Tensor:
	if rows.numel()==0:return torch.zeros((int(rows.shape[0]),),dtype=rows.dtype,device=rows.device)
	return torch.clamp(torch.sum(rows*rows,dim=-1),min=_SAFETY_EPS)
def build_safety_local_numpy(*,soc:np.ndarray,load_raw:np.ndarray,pv_raw:np.ndarray,battery_capacity_kwh:np.ndarray,p_max_kw:np.ndarray)->np.ndarray:return np.column_stack([np.asarray(soc,dtype=np.float32),np.asarray(load_raw,dtype=np.float32),np.asarray(pv_raw,dtype=np.float32),np.asarray(battery_capacity_kwh,dtype=np.float32),np.asarray(p_max_kw,dtype=np.float32)]).astype(np.float32)
def _canonicalize_actions_numpy(actions:np.ndarray|list[np.ndarray],*,default_pv_action:float=1.,require_full_action_dim:bool=False)->tuple[np.ndarray,bool]:
	action_array=np.asarray(actions,dtype=np.float32);squeezed=action_array.ndim==1
	if squeezed:action_array=action_array.reshape(1,-1)
	if action_array.ndim!=2:raise ValueError(f"Expected 2D action array, got shape {action_array.shape}.")
	if action_array.shape[-1]==1 and not require_full_action_dim:action_array=np.concatenate([action_array,np.full((action_array.shape[0],1),float(default_pv_action),dtype=np.float32)],axis=-1)
	elif action_array.shape[-1]!=2:raise ValueError(f"Expected action_dim=2, got shape {action_array.shape}.")
	return action_array.astype(np.float32,copy=False),squeezed
def _canonicalize_actions_torch(actions:torch.Tensor,*,default_pv_action:float=1.,require_full_action_dim:bool=False)->tuple[torch.Tensor,bool]:
	squeezed=actions.ndim==2
	if squeezed:actions=actions.unsqueeze(0)
	if actions.ndim!=3:raise ValueError(f"Expected action tensor rank 3, got shape {tuple(actions.shape)}.")
	if actions.shape[-1]==1 and not require_full_action_dim:actions=torch.cat([actions,torch.full((*actions.shape[:-1],1),float(default_pv_action),dtype=actions.dtype,device=actions.device)],dim=-1)
	elif actions.shape[-1]!=2:raise ValueError(f"Expected action_dim=2, got shape {tuple(actions.shape)}.")
	return actions,squeezed
def _local_bounds_numpy(safety_local:np.ndarray,*,efficiency:float,dt_hours:float,soc_min:float,soc_max:float)->tuple[np.ndarray,np.ndarray,np.ndarray,np.ndarray]:soc=np.clip(np.asarray(safety_local[...,0],dtype=np.float32),soc_min,soc_max);capacity_kwh=np.maximum(np.asarray(safety_local[...,3],dtype=np.float32),_SAFETY_EPS);p_max_kw=np.maximum(np.asarray(safety_local[...,4],dtype=np.float32),_SAFETY_EPS);pv_raw_kw=np.maximum(np.asarray(safety_local[...,2],dtype=np.float32),.0);energy_now=soc*capacity_kwh;eff=max(float(efficiency),_SAFETY_EPS);dt=max(float(dt_hours),_SAFETY_EPS);energy_min=float(soc_min)*capacity_kwh;energy_max=float(soc_max)*capacity_kwh;charge_limit_kw=np.minimum(p_max_kw,np.maximum(.0,(energy_max-energy_now)/(eff*dt)));discharge_limit_kw=np.minimum(p_max_kw,np.maximum(.0,(energy_now-energy_min)*eff/dt));return-discharge_limit_kw,charge_limit_kw,p_max_kw,pv_raw_kw
def _local_bounds_torch(safety_local:torch.Tensor,*,efficiency:float,dt_hours:float,soc_min:float,soc_max:float)->tuple[torch.Tensor,torch.Tensor,torch.Tensor,torch.Tensor]:soc=torch.clamp(safety_local[...,0],min=float(soc_min),max=float(soc_max));capacity_kwh=torch.clamp(safety_local[...,3],min=_SAFETY_EPS);p_max_kw=torch.clamp(safety_local[...,4],min=_SAFETY_EPS);pv_raw_kw=torch.clamp(safety_local[...,2],min=.0);energy_now=soc*capacity_kwh;eff=max(float(efficiency),_SAFETY_EPS);dt=max(float(dt_hours),_SAFETY_EPS);energy_min=float(soc_min)*capacity_kwh;energy_max=float(soc_max)*capacity_kwh;charge_limit_kw=torch.minimum(p_max_kw,torch.clamp((energy_max-energy_now)/(eff*dt),min=.0));discharge_limit_kw=torch.minimum(p_max_kw,torch.clamp((energy_now-energy_min)*eff/dt,min=.0));return-discharge_limit_kw,charge_limit_kw,p_max_kw,pv_raw_kw
def compute_action_gap_metrics_numpy(safety_local:np.ndarray,requested_actions:np.ndarray|list[np.ndarray],executed_actions:np.ndarray|list[np.ndarray])->dict[str,np.ndarray]:
	requested,squeezed=_canonicalize_actions_numpy(requested_actions);executed,_=_canonicalize_actions_numpy(executed_actions);safety_local=np.asarray(safety_local,dtype=np.float32)
	if safety_local.shape[0]!=requested.shape[0]:raise ValueError(f"safety_local and action arrays should share the same agent dimension, got {safety_local.shape} vs {requested.shape}.")
	p_max_kw=np.maximum(safety_local[:,4],_SAFETY_EPS);pv_raw_kw=np.maximum(safety_local[:,2],.0);battery_action_req,battery_action_exec=requested[:,0].astype(np.float32),executed[:,0].astype(np.float32);pv_action_exec=executed[:,1].astype(np.float32);battery_power_req_kw=(battery_action_req*p_max_kw).astype(np.float32);battery_power_exec_kw=(battery_action_exec*p_max_kw).astype(np.float32);pv_effective_req_kw=(.5*(requested[:,1].astype(np.float32)+1.)*pv_raw_kw).astype(np.float32);pv_effective_exec_kw=(.5*(pv_action_exec+1.)*pv_raw_kw).astype(np.float32);metrics={'battery_action_req':battery_action_req,'battery_action_exec':battery_action_exec,'controller_action_gap':np.linalg.norm(requested-executed,axis=-1).astype(np.float32),'battery_power_req_kw':battery_power_req_kw,'battery_power_exec_kw':battery_power_exec_kw,'pv_action_exec':pv_action_exec,'pv_effective_req_kw':pv_effective_req_kw,'pv_effective_exec_kw':pv_effective_exec_kw,'pv_curtail_req_kw':(pv_raw_kw-pv_effective_req_kw).astype(np.float32),'pv_curtail_exec_kw':(pv_raw_kw-pv_effective_exec_kw).astype(np.float32),'soc_penalty_unweighted':(np.abs(battery_power_req_kw-battery_power_exec_kw)/(p_max_kw+_SAFETY_EPS)).astype(np.float32)};return{key:np.asarray(value[0],dtype=np.float32)for(key,value)in metrics.items()}if squeezed else metrics
def compute_action_gap_metrics_torch(safety_local:torch.Tensor,requested_actions:torch.Tensor,executed_actions:torch.Tensor)->dict[str,torch.Tensor]:
	requested,squeezed=_canonicalize_actions_torch(requested_actions);executed,_=_canonicalize_actions_torch(executed_actions)
	if int(safety_local.shape[0])!=int(requested.shape[0]):raise ValueError(f"safety_local batch dimension should match requested_actions batch dimension, got {tuple(safety_local.shape)} vs {tuple(requested.shape)}.")
	p_max_kw=torch.clamp(safety_local[...,4],min=_SAFETY_EPS);pv_raw_kw=torch.clamp(safety_local[...,2],min=.0);battery_power_req_kw=requested[...,0]*p_max_kw;battery_power_exec_kw=executed[...,0]*p_max_kw;pv_action_exec=executed[...,1];pv_effective_req_kw=.5*(requested[...,1]+1.)*pv_raw_kw;pv_effective_exec_kw=.5*(pv_action_exec+1.)*pv_raw_kw;metrics={'battery_action_req':requested[...,0],'battery_action_exec':executed[...,0],'controller_action_gap':torch.linalg.norm(requested-executed,dim=-1),'battery_power_req_kw':battery_power_req_kw,'battery_power_exec_kw':battery_power_exec_kw,'pv_action_exec':pv_action_exec,'pv_effective_req_kw':pv_effective_req_kw,'pv_effective_exec_kw':pv_effective_exec_kw,'pv_curtail_req_kw':pv_raw_kw-pv_effective_req_kw,'pv_curtail_exec_kw':pv_raw_kw-pv_effective_exec_kw,'soc_penalty_unweighted':(battery_power_req_kw-battery_power_exec_kw).abs()/torch.clamp(p_max_kw,min=_SAFETY_EPS)};return{key:value.squeeze(0)for(key,value)in metrics.items()}if squeezed else metrics
def enforce_local_action_feasibility_torch(safety_local:torch.Tensor,raw_actions:torch.Tensor,*,efficiency:float,dt_hours:float,soc_min:float,soc_max:float)->tuple[torch.Tensor,dict[str,torch.Tensor]]:requested_actions,squeezed=_canonicalize_actions_torch(raw_actions);battery_lower_kw,battery_upper_kw,p_max_kw,_=_local_bounds_torch(safety_local,efficiency=efficiency,dt_hours=dt_hours,soc_min=soc_min,soc_max=soc_max);executed_actions=torch.stack([torch.clamp(requested_actions[...,0]*p_max_kw,min=battery_lower_kw,max=battery_upper_kw)/torch.clamp(p_max_kw,min=_SAFETY_EPS),torch.clamp(requested_actions[...,1],min=-1.,max=1.)],dim=-1);metrics=compute_action_gap_metrics_torch(safety_local,requested_actions,executed_actions);return(executed_actions.squeeze(0),metrics)if squeezed else(executed_actions,metrics)
def action_info_to_numpy(action_info:dict[str,torch.Tensor]|None)->dict[str,np.ndarray]|None:
	if action_info is None:return
	return{key:value.detach().to(dtype=torch.float32).cpu().numpy()if isinstance(value,torch.Tensor)else np.asarray(value,dtype=np.float32)for(key,value)in action_info.items()}
def merge_action_info_into_step_info(info:dict[str,Any],action_info:dict[str,np.ndarray]|None)->dict[str,Any]:
	reject_removed_step_info_fields(info,entrypoint='merge_action_info_into_step_info')
	updated=dict(info)
	if action_info is None:return updated
	reject_removed_step_info_fields(action_info,entrypoint='merge_action_info_into_step_info(action_info)')
	updated.update({key:np.asarray(value,dtype=np.float32)for(key,value)in action_info.items()})
	for(source_key,target_key)in{'battery_power_req_kw':'e_bat_req','battery_power_exec_kw':'e_bat','pv_effective_req_kw':'pv_effective_req','pv_effective_exec_kw':'pv_effective','pv_curtail_req_kw':'pv_curtail_req','pv_curtail_exec_kw':'pv_curtail','pv_action_exec':'pv_action'}.items():
		if source_key in action_info:updated[target_key]=np.asarray(action_info[source_key],dtype=np.float32)
	return updated
def validate_executed_actions_numpy(safety_local:np.ndarray,actions:np.ndarray|list[np.ndarray],*,efficiency:float,dt_hours:float,soc_min:float,soc_max:float)->None:
	action_array,_=_canonicalize_actions_numpy(actions,require_full_action_dim=True)
	if np.any(~np.isfinite(action_array)):raise ValueError('Environment received non-finite action values.')
	if np.any(action_array<-1.-_ACTION_TOL)or np.any(action_array>1.+_ACTION_TOL):raise ValueError('Environment received action values outside [-1, 1]. Controllers must output already-feasible normalized actions.')
	battery_lower_kw,battery_upper_kw,p_max_kw,pv_raw_kw=_local_bounds_numpy(safety_local,efficiency=efficiency,dt_hours=dt_hours,soc_min=soc_min,soc_max=soc_max);battery_power_kw=action_array[:,0]*p_max_kw;invalid_battery=np.logical_or(battery_power_kw<battery_lower_kw-_ACTION_TOL,battery_power_kw>battery_upper_kw+_ACTION_TOL)
	if np.any(invalid_battery):bad_agent=int(np.nonzero(invalid_battery)[0][0]);raise ValueError(f"Environment received a locally infeasible battery action for agent {bad_agent}: requested {battery_power_kw[bad_agent]:.4f} kW, allowed range [{battery_lower_kw[bad_agent]:.4f}, {battery_upper_kw[bad_agent]:.4f}] kW.")
	pv_effective_kw=.5*(action_array[:,1]+1.)*pv_raw_kw;invalid_pv=np.logical_or(pv_effective_kw<-_ACTION_TOL,pv_effective_kw>pv_raw_kw+_ACTION_TOL)
	if np.any(invalid_pv):bad_agent=int(np.nonzero(invalid_pv)[0][0]);raise ValueError(f"Environment received a locally infeasible PV action for agent {bad_agent}: effective PV {pv_effective_kw[bad_agent]:.4f} kW, valid range [0.0000, {pv_raw_kw[bad_agent]:.4f}] kW.")
class JointGridSafetyProjector(nn.Module):
	def __init__(self,*,n_agents:int,voltage_sensitivity:np.ndarray,line_loading_sensitivity:np.ndarray,trafo_power_sensitivity:np.ndarray,voltage_base:np.ndarray,line_loading_base:np.ndarray,trafo_power_base_kw:np.ndarray,voltage_min_pu:float,voltage_max_pu:float,line_limit_pct:float,trafo_limit_pct:float,trafo_rating_kw:np.ndarray,efficiency:float,dt_hours:float,soc_min:float,soc_max:float,projector_mode:str,projection_iters:int,voltage_margin_pu:float,line_margin_pct:float,trafo_margin_pct:float,linearization_delta_kw:float)->None:
		super().__init__();self.n_agents=int(n_agents);self.projector_mode=str(projector_mode);self.projection_iters=max(int(projection_iters),1);self.voltage_min_pu=float(voltage_min_pu);self.voltage_max_pu=float(voltage_max_pu);self.line_limit_pct=float(line_limit_pct);self.trafo_limit_pct=float(trafo_limit_pct);self.efficiency=float(efficiency);self.dt_hours=float(dt_hours);self.soc_min=float(soc_min);self.soc_max=float(soc_max);self.voltage_margin_pu=float(voltage_margin_pu);self.line_margin_pct=float(line_margin_pct);self.trafo_margin_pct=float(trafo_margin_pct);voltage_sensitivity_t=torch.as_tensor(voltage_sensitivity,dtype=torch.float32);line_loading_sensitivity_t=torch.as_tensor(line_loading_sensitivity,dtype=torch.float32);trafo_power_sensitivity_t=torch.as_tensor(trafo_power_sensitivity,dtype=torch.float32);self.register_buffer('voltage_sensitivity',voltage_sensitivity_t);self.register_buffer('line_loading_sensitivity',line_loading_sensitivity_t);self.register_buffer('trafo_power_sensitivity',trafo_power_sensitivity_t);self.register_buffer('voltage_base',torch.as_tensor(voltage_base,dtype=torch.float32));self.register_buffer('line_loading_base',torch.as_tensor(line_loading_base,dtype=torch.float32));self.register_buffer('trafo_power_base_kw',torch.as_tensor(trafo_power_base_kw,dtype=torch.float32));trafo_rating_kw_t=torch.as_tensor(trafo_rating_kw,dtype=torch.float32);trafo_limit_kw_t=trafo_rating_kw_t*(self.trafo_limit_pct/1e2);trafo_usable_limit_kw_t=trafo_limit_kw_t*max(.0,1.-self.trafo_margin_pct/1e2);self.register_buffer('trafo_import_limit_kw',trafo_usable_limit_kw_t.clone());self.register_buffer('trafo_export_limit_kw',trafo_usable_limit_kw_t.clone());self.register_buffer('voltage_rows_upper',voltage_sensitivity_t.clone());self.register_buffer('voltage_rows_lower',-voltage_sensitivity_t.clone());self.register_buffer('line_rows',line_loading_sensitivity_t.clone());self.register_buffer('trafo_rows_import',trafo_power_sensitivity_t.clone());self.register_buffer('trafo_rows_export',-trafo_power_sensitivity_t.clone());self.register_buffer('voltage_row_norm_sq',_row_norm_sq(voltage_sensitivity_t));self.register_buffer('line_row_norm_sq',_row_norm_sq(line_loading_sensitivity_t));self.register_buffer('trafo_row_norm_sq',_row_norm_sq(trafo_power_sensitivity_t));combined_rows=[voltage_sensitivity_t,-voltage_sensitivity_t]
		if line_loading_sensitivity_t.numel()>0:combined_rows.append(line_loading_sensitivity_t)
		if trafo_power_sensitivity_t.numel()>0:combined_rows.append(trafo_power_sensitivity_t);combined_rows.append(-trafo_power_sensitivity_t)
		combined_constraint_rows=torch.cat(combined_rows,dim=0);self.register_buffer('combined_constraint_rows',combined_constraint_rows);self.register_buffer('combined_constraint_row_norm_sq',_row_norm_sq(combined_constraint_rows))
	@classmethod
	def from_cfg(cls,cfg:Any,*,device:torch.device|str|None=None)->'JointGridSafetyProjector':
		deployments=build_agent_deployments(cfg);grid_core=GridCore(deployments,cfg.grid);n_agents=int(len(deployments));delta_kw=max(float(getattr(cfg.safety,'linearization_delta_kw',.25)),.05);zero=np.zeros(n_agents,dtype=np.float32);grid_core.reset(zero,zero);baseline=grid_core.step(zero,zero);net_voltage_sensitivity=np.zeros((grid_core.n_buses,n_agents),dtype=np.float32);net_line_loading_sensitivity=np.zeros((grid_core.n_lines,n_agents),dtype=np.float32);trafo_power_available=bool(grid_core.n_trafos>0 and hasattr(grid_core.net,'res_trafo')and'p_hv_mw'in getattr(grid_core.net,'res_trafo').columns)
		if trafo_power_available:net_trafo_power_sensitivity=np.zeros((grid_core.n_trafos,n_agents),dtype=np.float32);trafo_power_base_kw=np.asarray(baseline.trafo_p_signed_kw,dtype=np.float32);trafo_rating_kw=np.asarray(grid_core.net.trafo['sn_mva'].to_numpy(dtype=np.float32),dtype=np.float32)*1e3
		else:net_trafo_power_sensitivity=np.zeros((0,n_agents),dtype=np.float32);trafo_power_base_kw=np.zeros(0,dtype=np.float32);trafo_rating_kw=np.zeros(0,dtype=np.float32)
		for agent_id in range(n_agents):
			perturb=zero.copy();perturb[agent_id]=np.float32(delta_kw);grid_core.reset(zero,zero);result_plus=grid_core.step(perturb,zero);grid_core.reset(zero,zero);result_minus=grid_core.step(-perturb,zero);net_voltage_sensitivity[:,agent_id]=(np.asarray(result_plus.vm_pu,dtype=np.float32)-np.asarray(baseline.vm_pu,dtype=np.float32))/np.float32(delta_kw)
			if grid_core.n_lines>0:net_line_loading_sensitivity[:,agent_id]=(np.asarray(result_plus.line_loading_pct,dtype=np.float32)-np.asarray(baseline.line_loading_pct,dtype=np.float32))/np.float32(delta_kw)
			if trafo_power_available:net_trafo_power_sensitivity[:,agent_id]=(np.asarray(result_plus.trafo_p_signed_kw,dtype=np.float32)-np.asarray(result_minus.trafo_p_signed_kw,dtype=np.float32))/np.float32(2.*delta_kw)
		voltage_sensitivity=np.concatenate([net_voltage_sensitivity,net_voltage_sensitivity],axis=1);line_loading_sensitivity=np.concatenate([net_line_loading_sensitivity,net_line_loading_sensitivity],axis=1);trafo_power_sensitivity=np.concatenate([net_trafo_power_sensitivity,net_trafo_power_sensitivity],axis=1);projector=cls(n_agents=n_agents,voltage_sensitivity=voltage_sensitivity,line_loading_sensitivity=line_loading_sensitivity,trafo_power_sensitivity=trafo_power_sensitivity,voltage_base=np.asarray(baseline.vm_pu,dtype=np.float32),line_loading_base=np.asarray(baseline.line_loading_pct,dtype=np.float32),trafo_power_base_kw=trafo_power_base_kw,voltage_min_pu=float(cfg.grid.v_min_pu),voltage_max_pu=float(cfg.grid.v_max_pu),line_limit_pct=float(cfg.grid.line_max_loading_pct),trafo_limit_pct=float(cfg.grid.line_max_loading_pct),trafo_rating_kw=trafo_rating_kw,efficiency=float(cfg.env.efficiency),dt_hours=float(cfg.env.dt),soc_min=float(cfg.env.soc_min),soc_max=float(cfg.env.soc_max),projector_mode=str(getattr(cfg.safety,'projector_mode','joint_linearized')),projection_iters=int(getattr(cfg.safety,'projection_iters',6)),voltage_margin_pu=float(getattr(cfg.safety,'voltage_margin_pu',.005)),line_margin_pct=float(getattr(cfg.safety,'line_margin_pct',5.)),trafo_margin_pct=float(getattr(cfg.safety,'trafo_margin_pct',5.)),linearization_delta_kw=delta_kw)
		if device is not None:projector=projector.to(device=torch.device(device))
		return projector
	@staticmethod
	def _as_work_dtype(buffer:torch.Tensor,*,dtype:torch.dtype,device:torch.device)->torch.Tensor:
		if buffer.dtype==dtype and buffer.device==device:return buffer
		return buffer.to(device=device,dtype=dtype)
	def _affine_terms(self,safety_local:torch.Tensor,*,dtype:torch.dtype,device:torch.device)->tuple[torch.Tensor,torch.Tensor,torch.Tensor]:
		base_net_load_kw=(safety_local[...,1]-safety_local[...,2]).to(dtype=dtype);voltage_sensitivity=self._as_work_dtype(self.voltage_sensitivity,dtype=dtype,device=device)[:,:self.n_agents];line_sensitivity=self._as_work_dtype(self.line_loading_sensitivity,dtype=dtype,device=device)[:,:self.n_agents];trafo_sensitivity=self._as_work_dtype(self.trafo_power_sensitivity,dtype=dtype,device=device)[:,:self.n_agents];voltage_base=self._as_work_dtype(self.voltage_base,dtype=dtype,device=device);line_base=self._as_work_dtype(self.line_loading_base,dtype=dtype,device=device);trafo_base=self._as_work_dtype(self.trafo_power_base_kw,dtype=dtype,device=device);voltage_affine=voltage_base.unsqueeze(0)+base_net_load_kw@voltage_sensitivity.transpose(0,1);line_affine=line_base.unsqueeze(0)
		if line_sensitivity.numel()>0:line_affine=line_affine+base_net_load_kw@line_sensitivity.transpose(0,1)
		trafo_affine=trafo_base.unsqueeze(0)
		if trafo_sensitivity.numel()>0:trafo_affine=trafo_affine+base_net_load_kw@trafo_sensitivity.transpose(0,1)
		return voltage_affine,line_affine,trafo_affine
	def _trafo_power_violation_terms(self,*,x_kw:torch.Tensor,trafo_affine:torch.Tensor,dtype:torch.dtype,device:torch.device)->tuple[torch.Tensor,torch.Tensor]:
		batch_size=int(x_kw.shape[0]);zero=torch.zeros((batch_size,),dtype=dtype,device=device);trafo_sensitivity=self._as_work_dtype(self.trafo_power_sensitivity,dtype=dtype,device=device)
		if trafo_sensitivity.numel()==0 or trafo_affine.shape[-1]==0:return zero,zero
		trafo_import_limit_kw=self._as_work_dtype(self.trafo_import_limit_kw,dtype=dtype,device=device);trafo_export_limit_kw=self._as_work_dtype(self.trafo_export_limit_kw,dtype=dtype,device=device);trafo_power=trafo_affine+x_kw@trafo_sensitivity.transpose(0,1);import_violation=torch.sum(torch.clamp(trafo_power-trafo_import_limit_kw.unsqueeze(0),min=.0),dim=-1);export_violation=torch.sum(torch.clamp(-trafo_power-trafo_export_limit_kw.unsqueeze(0),min=.0),dim=-1);return import_violation,export_violation
	def _approximate_violation(self,*,x_kw:torch.Tensor,voltage_affine:torch.Tensor,line_affine:torch.Tensor,trafo_affine:torch.Tensor,dtype:torch.dtype,device:torch.device)->torch.Tensor:
		voltage_sensitivity=self._as_work_dtype(self.voltage_sensitivity,dtype=dtype,device=device);line_sensitivity=self._as_work_dtype(self.line_loading_sensitivity,dtype=dtype,device=device);voltage=voltage_affine+x_kw@voltage_sensitivity.transpose(0,1);voltage_high=torch.clamp(voltage-(self.voltage_max_pu-self.voltage_margin_pu),min=.0);voltage_low=torch.clamp(self.voltage_min_pu+self.voltage_margin_pu-voltage,min=.0);line_violation=torch.zeros((x_kw.shape[0],),dtype=dtype,device=device)
		if line_sensitivity.numel()>0:line_loading=line_affine+x_kw@line_sensitivity.transpose(0,1);line_violation=torch.sum(torch.clamp(line_loading-(self.line_limit_pct-self.line_margin_pct),min=.0),dim=-1)
		trafo_import_violation,trafo_export_violation=self._trafo_power_violation_terms(x_kw=x_kw,trafo_affine=trafo_affine,dtype=dtype,device=device);trafo_violation=trafo_import_violation+trafo_export_violation;return torch.sum(voltage_high+voltage_low,dim=-1)+line_violation+trafo_violation
	def _project_rows_sequential(self,x_kw:torch.Tensor,rows:torch.Tensor,bounds:torch.Tensor,row_norm_sq:torch.Tensor)->torch.Tensor:
		if rows.numel()==0 or bounds.numel()==0:return x_kw
		valid_indices=torch.nonzero(row_norm_sq>_SAFETY_EPS,as_tuple=False).squeeze(-1)
		for idx in valid_indices.tolist():row=rows[idx];bound=bounds[:,idx];violation=torch.sum(x_kw*row.unsqueeze(0),dim=-1)-bound;correction=torch.clamp(violation,min=.0).unsqueeze(-1)*row.unsqueeze(0)/row_norm_sq[idx];x_kw=x_kw-correction
		return x_kw
	def _project_rows_batched(self,x_kw:torch.Tensor,rows:torch.Tensor,bounds:torch.Tensor,row_norm_sq:torch.Tensor)->torch.Tensor:
		if rows.numel()==0 or bounds.numel()==0:return x_kw
		valid_rows=row_norm_sq>_SAFETY_EPS
		if not torch.any(valid_rows):return x_kw
		rows=rows[valid_rows];bounds=bounds[:,valid_rows];row_norm_sq=row_norm_sq[valid_rows];violations=x_kw@rows.transpose(0,1)-bounds;correction_weights=torch.clamp(violations,min=.0)/row_norm_sq.unsqueeze(0);return x_kw-correction_weights@rows
	def _combined_bounds(self,*,voltage_affine:torch.Tensor,line_affine:torch.Tensor,trafo_affine:torch.Tensor,voltage_low_limit:float,voltage_high_limit:float,line_limit:float,trafo_import_limit_kw:torch.Tensor,trafo_export_limit_kw:torch.Tensor)->torch.Tensor:
		bounds=[voltage_high_limit-voltage_affine,voltage_affine-voltage_low_limit]
		if line_affine.shape[-1]>0:bounds.append(line_limit-line_affine)
		if trafo_affine.shape[-1]>0:bounds.append(trafo_import_limit_kw.unsqueeze(0)-trafo_affine);bounds.append(trafo_export_limit_kw.unsqueeze(0)+trafo_affine)
		return torch.cat(bounds,dim=-1)
	@staticmethod
	def _clamp_joint_action_kw(x_kw:torch.Tensor,*,battery_lower_kw:torch.Tensor,battery_upper_kw:torch.Tensor,pv_curtail_upper_kw:torch.Tensor,n_agents:int)->torch.Tensor:battery_kw=torch.clamp(x_kw[...,:n_agents],min=battery_lower_kw,max=battery_upper_kw);pv_curtail_kw=torch.maximum(x_kw[...,n_agents:],torch.zeros_like(pv_curtail_upper_kw));pv_curtail_kw=torch.minimum(pv_curtail_kw,pv_curtail_upper_kw);return torch.cat([battery_kw,pv_curtail_kw],dim=-1)
	def project_actions(self,obs:dict[str,torch.Tensor]|dict[str,np.ndarray],raw_actions:torch.Tensor,*,return_diagnostics:bool=False):
		if'safety_local'not in obs:raise KeyError("project_actions requires obs['safety_local'].")
		return self.project_actions_from_safety_local(torch.as_tensor(obs['safety_local'],dtype=raw_actions.dtype,device=raw_actions.device),raw_actions,return_diagnostics=return_diagnostics)
	def project_actions_from_safety_local(self,safety_local:torch.Tensor,raw_actions:torch.Tensor,*,return_diagnostics:bool=False)->torch.Tensor|tuple[torch.Tensor,dict[str,float|int|bool]]:
		squeezed=raw_actions.ndim==2
		if squeezed:raw_actions=raw_actions.unsqueeze(0)
		if safety_local.ndim==2:safety_local=safety_local.unsqueeze(0)
		if int(safety_local.shape[0])!=int(raw_actions.shape[0]):raise ValueError('safety_local batch dimension must match raw_actions batch dimension for safety projection.')
		original_dtype=raw_actions.dtype;device=raw_actions.device;work_dtype=torch.float32 if raw_actions.dtype in{torch.float16,torch.bfloat16}else raw_actions.dtype;safety_local=safety_local.to(device=device,dtype=work_dtype);battery_action=raw_actions[...,0].to(dtype=work_dtype)
		if raw_actions.shape[-1]>=2:pv_action=raw_actions[...,1].to(dtype=work_dtype)
		else:pv_action=torch.ones_like(battery_action,dtype=work_dtype)
		battery_lower_kw,battery_upper_kw,p_max_kw,pv_raw_kw=_local_bounds_torch(safety_local,efficiency=self.efficiency,dt_hours=self.dt_hours,soc_min=self.soc_min,soc_max=self.soc_max);raw_battery_kw=battery_action*p_max_kw;raw_pv_utilization=torch.clamp(.5*(pv_action+1.),min=.0,max=1.);raw_pv_curtail_kw=pv_raw_kw*(1.-raw_pv_utilization);raw_kw=torch.cat([raw_battery_kw,raw_pv_curtail_kw],dim=-1);x_kw=self._clamp_joint_action_kw(raw_kw,battery_lower_kw=battery_lower_kw,battery_upper_kw=battery_upper_kw,pv_curtail_upper_kw=pv_raw_kw,n_agents=self.n_agents);voltage_affine,line_affine,trafo_affine=self._affine_terms(safety_local,dtype=work_dtype,device=device);pre_violation=None
		if return_diagnostics:pre_violation=self._approximate_violation(x_kw=raw_kw,voltage_affine=voltage_affine,line_affine=line_affine,trafo_affine=trafo_affine,dtype=work_dtype,device=device)
		voltage_rows_upper=self._as_work_dtype(self.voltage_rows_upper,dtype=work_dtype,device=device);voltage_rows_lower=self._as_work_dtype(self.voltage_rows_lower,dtype=work_dtype,device=device);line_rows=self._as_work_dtype(self.line_rows,dtype=work_dtype,device=device);trafo_rows_import=self._as_work_dtype(self.trafo_rows_import,dtype=work_dtype,device=device);trafo_rows_export=self._as_work_dtype(self.trafo_rows_export,dtype=work_dtype,device=device);voltage_row_norm_sq=self._as_work_dtype(self.voltage_row_norm_sq,dtype=work_dtype,device=device);line_row_norm_sq=self._as_work_dtype(self.line_row_norm_sq,dtype=work_dtype,device=device);trafo_row_norm_sq=self._as_work_dtype(self.trafo_row_norm_sq,dtype=work_dtype,device=device);combined_constraint_rows=self._as_work_dtype(self.combined_constraint_rows,dtype=work_dtype,device=device);combined_constraint_row_norm_sq=self._as_work_dtype(self.combined_constraint_row_norm_sq,dtype=work_dtype,device=device);voltage_low_limit=self.voltage_min_pu+self.voltage_margin_pu;voltage_high_limit=self.voltage_max_pu-self.voltage_margin_pu;line_limit=self.line_limit_pct-self.line_margin_pct;trafo_import_limit_kw=self._as_work_dtype(self.trafo_import_limit_kw,dtype=work_dtype,device=device);trafo_export_limit_kw=self._as_work_dtype(self.trafo_export_limit_kw,dtype=work_dtype,device=device)
		for _ in range(self.projection_iters):
			x_kw=self._clamp_joint_action_kw(x_kw,battery_lower_kw=battery_lower_kw,battery_upper_kw=battery_upper_kw,pv_curtail_upper_kw=pv_raw_kw,n_agents=self.n_agents)
			if self.projector_mode=='joint_linearized_fast':combined_bounds=self._combined_bounds(voltage_affine=voltage_affine,line_affine=line_affine,trafo_affine=trafo_affine,voltage_low_limit=voltage_low_limit,voltage_high_limit=voltage_high_limit,line_limit=line_limit,trafo_import_limit_kw=trafo_import_limit_kw,trafo_export_limit_kw=trafo_export_limit_kw);x_kw=self._project_rows_batched(x_kw,combined_constraint_rows,combined_bounds,combined_constraint_row_norm_sq);continue
			x_kw=self._project_rows_sequential(x_kw,voltage_rows_upper,voltage_high_limit-voltage_affine,voltage_row_norm_sq);x_kw=self._project_rows_sequential(x_kw,voltage_rows_lower,voltage_affine-voltage_low_limit,voltage_row_norm_sq);x_kw=self._project_rows_sequential(x_kw,line_rows,line_limit-line_affine,line_row_norm_sq);x_kw=self._project_rows_sequential(x_kw,trafo_rows_import,trafo_import_limit_kw.unsqueeze(0)-trafo_affine,trafo_row_norm_sq);x_kw=self._project_rows_sequential(x_kw,trafo_rows_export,trafo_export_limit_kw.unsqueeze(0)+trafo_affine,trafo_row_norm_sq)
		x_kw=self._clamp_joint_action_kw(x_kw,battery_lower_kw=battery_lower_kw,battery_upper_kw=battery_upper_kw,pv_curtail_upper_kw=pv_raw_kw,n_agents=self.n_agents);projected_battery_kw=x_kw[...,:self.n_agents];projected_pv_curtail_kw=x_kw[...,self.n_agents:];projected_battery_action=torch.clamp(projected_battery_kw/torch.clamp(p_max_kw,min=_SAFETY_EPS),min=-1.,max=1.);projected_pv_utilization=torch.ones_like(projected_pv_curtail_kw,dtype=work_dtype);valid_pv_mask=pv_raw_kw>_SAFETY_EPS;projected_pv_utilization[valid_pv_mask]=1.-projected_pv_curtail_kw[valid_pv_mask]/torch.clamp(pv_raw_kw[valid_pv_mask],min=_SAFETY_EPS);projected_pv_utilization=torch.clamp(projected_pv_utilization,min=.0,max=1.);projected_pv_action=torch.clamp(2.*projected_pv_utilization-1.,min=-1.,max=1.);projected_actions=torch.stack([projected_battery_action,projected_pv_action],dim=-1)
		if raw_actions.shape[-1]>2:projected_actions=torch.cat([projected_actions,raw_actions[...,2:]],dim=-1)
		projected_actions=projected_actions.to(dtype=original_dtype)
		if squeezed:projected_actions=projected_actions.squeeze(0)
		if not return_diagnostics:return projected_actions
		post_violation=self._approximate_violation(x_kw=x_kw,voltage_affine=voltage_affine,line_affine=line_affine,trafo_affine=trafo_affine,dtype=work_dtype,device=device);pre_trafo_import_violation=torch.zeros_like(post_violation);pre_trafo_export_violation=torch.zeros_like(post_violation)
		if pre_violation is not None:pre_trafo_import_violation,pre_trafo_export_violation=self._trafo_power_violation_terms(x_kw=raw_kw,trafo_affine=trafo_affine,dtype=work_dtype,device=device)
		post_trafo_import_violation,post_trafo_export_violation=self._trafo_power_violation_terms(x_kw=x_kw,trafo_affine=trafo_affine,dtype=work_dtype,device=device);raw_action_slice=raw_actions[...,:projected_actions.shape[-1]].to(dtype=work_dtype);projected_action_slice=projected_actions.unsqueeze(0).to(dtype=work_dtype)if squeezed else projected_actions.to(dtype=work_dtype);delta=(projected_action_slice-raw_action_slice).abs();delta_kw=(x_kw-raw_kw).abs();projected_any=torch.any(delta.reshape(delta.shape[0],-1)>1e-05,dim=-1);return projected_actions,{'enabled':True,'batch_size':int(battery_action.shape[0]),'projected_fraction':float(projected_any.float().mean().item()),'mean_abs_delta':float(delta.mean().item()),'max_abs_delta':float(delta.max().item()),'mean_abs_delta_kw':float(delta_kw.mean().item()),'pre_violation':float(pre_violation.mean().item())if pre_violation is not None else .0,'post_violation':float(post_violation.mean().item()),'pre_trafo_import_violation_kw':float(pre_trafo_import_violation.mean().item()),'pre_trafo_export_violation_kw':float(pre_trafo_export_violation.mean().item()),'post_trafo_import_violation_kw':float(post_trafo_import_violation.mean().item()),'post_trafo_export_violation_kw':float(post_trafo_export_violation.mean().item())}
